// <auto-generated />
using System;
using AnalyzerDomain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AnalyzerDomain.Migrations
{
    [DbContext(typeof(AnalyzerContext))]
    [Migration("20210417104248_Add-AnalysisType-simple")]
    partial class AddAnalysisTypesimple
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.14");

            modelBuilder.Entity("AnalyzerDomain.Models.AnalysisType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CartridgeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CartridgeId");

                    b.ToTable("AnalysisTypes");
                });

            modelBuilder.Entity("AnalyzerDomain.Models.Cartridge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Barcode")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Cartridges");
                });

            modelBuilder.Entity("AnalyzerDomain.Models.AnalysisType", b =>
                {
                    b.HasOne("AnalyzerDomain.Models.Cartridge", "Cartridge")
                        .WithMany("AnalyzesTypes")
                        .HasForeignKey("CartridgeId");
                });
#pragma warning restore 612, 618
        }
    }
}
